verbatim:
  cabal-version: 3.0

name:    openapi-specgen
version: "0"

dependencies:
  - base
  - template-haskell
  - openapi3
  - text
  - aeson
  - insert-ordered-containers
  - lens
  
library:
  source-dirs: src

executables:
  openapi-specgen:
    main: Main.hs
    source-dirs:
      - app
    dependencies:
    - openapi-specgen

tests:
  test:
    main: Main.hs
    source-dirs:
      - test
    dependencies:
    - QuickCheck
    - hspec


